### ISSUE TITLE
README setup instructions are confusing

### ISSUE THREAD

**Issue by chcorbato** [rosin-project/metacontrol_sim#44]
Because there are two sections: "Setup using wstool" and "Manually setup", I though I could simply follow one of them, so I did with wstool.
But you actually need to do BOTH.

I propose to have a single "Installation and setup section", and introduce both sets of instructions with a sentence in normal text, not as a header.

**Comment by marioney** [comment]
> But you actually need to do BOTH.

Then there's something missing on the `wstool` because it should already install everything.

Do you remember what was missing from the wstool?

**Comment by chcorbato** [comment]
> Do you remember what was missing from the wstool?

Based on the errors I got, that I fixed installing the following with `apt`:
- `map_server`
- `fake_localization`
- `laser_filters`

**Comment by chcorbato** [comment]
Bring here the discussion about the Set Up instructions:
https://github.com/rosin-project/metacontrol_experiments/issues/14

**Comment by marioney** [comment]
I've removed the Manual setup section in https://github.com/rosin-project/metacontrol_sim/commit/53c5ae249b247d01e902b4af4e4b8607c214f59d, I should work now with the wstools.

**Comment by darkobozhinoski** [comment]
> > Do you remember what was missing from the wstool?
> 
> Based on the errors I got, that I fixed installing the following with `apt`:
> 
> * `map_server`
> * `fake_localization`
> * `laser_filters`
> 
> I was going carzy because I thought I had already posted this in a issue, now I see you already saw [it](https://github.com/rosin-project/metacontrol_experiments/issues/14#issuecomment-669856506) :-D

This is still an issue. I needed to install these packages manually.

**Comment by darkobozhinoski** [comment]
> > > Do you remember what was missing from the wstool?
> > 
> > 
> > Based on the errors I got, that I fixed installing the following with `apt`:
> > 
> > * `map_server`
> > * `fake_localization`
> > * `laser_filters`
> > 
> > I was going carzy because I thought I had already posted this in a issue, now I see you already saw [it](https://github.com/rosin-project/metacontrol_experiments/issues/14#issuecomment-669856506) :-D
> 
> @marioney, This is still an issue. I needed to install these packages manually.

**Comment by marioney** [comment]
> @marioney This is still an issue. I needed to install these packages manually.

I see now  https://github.com/rosin-project/metacontrol_experiments is not in the [metacontrol_sim.rosinstall](https://github.com/rosin-project/metacontrol_sim/blob/MVP_world/metacontrol_sim.rosinstall) file. I think I added the dependencies in the wrong repo, they should be here.

**Comment by marioney** [comment]
OK, I've added the dependencies to this repo in https://github.com/rosin-project/metacontrol_sim/commit/08f8c5cf3f1b25d5a50dcba8e6076d686da1411f

rosdep should install everything now
